apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-motioneye-etc
  labels:
    type: nfs
spec:
  storageClassName: "nfs-storage"
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /data/k8s/prod/motioneye/etc
    server: 10.1.1.94
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-motioneye-lib
  labels:
    type: nfs
spec:
  storageClassName: "nfs-storage"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/k8s/prod/motioneye/etc
    server: 10.1.1.94
    readOnly: false
