kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motioneye-etc-pv-claim
  namespace: motioneye
spec:
  storageClassName: "nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motioneye-lib-pv-claim
  namespace: motioneye
spec:
  storageClassName: "nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
