apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nodered-data
  labels:
    type: nfs
spec:
  storageClassName: "nfs-storage"
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /data/k8s/prod/nodered/data
    server: 10.1.1.94
    readOnly: false

